title: Ritika Kumari
email: your-email@example.com
description: >
  Personal website powered by Jekyll
baseurl: ""
url: "https://riti1302.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
